### PR TITLE
Data visualisation of GP patient survey data

### PR DESCRIPTION
**Pull request by maryamanuel1**
Could you review please?

Mary

### CODE REVIEW

**Comment by maryamanuel1** [comment]
HI @craig-shenton 

Could you please review? I've done this in Jupyter Lab because plotly doesn't run on Jupyter notebook.

Thanks

Mary

**Comment by maryamanuel1** [comment]
@craig-shenton  - FYI "Data Visualisation of GP Patient Survey data" is the main file

**Comment by maryamanuel1** [comment]
@craig-shenton - I added a Added stacked percentage chart for appointments data to replace the stacked bar with survey numbers/

**Review by craig-shenton — APPROVED** [review]
👍

**Pull request merged**
